name: Python 3.10 Nginx Build Base Image Build on Push

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to apply to this build. Defaults to 'latest_310'."
        default: "latest_310"
        required: false
  push:
    paths:
      - python3.10/**
  schedule:
    - cron: '0 10 * * 0' # Weekly on Sunday at 00:10

jobs:
  PythonBuildBase:
    name: Build Python 3.10 build base image
    uses: uc-cdis/.github/.github/workflows/image_build_push.yaml@master
    with:
      DOCKERFILE_LOCATION: "./python3.10/Dockerfile"
      OVERRIDE_REPO_NAME: "python-nginx-al"
      OVERRIDE_TAG_NAME: "$(echo ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || format('{0}', github.head_ref || github.ref_name) }} | tr / _)"
      DOCKERFILE_BUILD_CONTEXT: "./python3.10"
    secrets: inherit
